---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/pharmakonlife/public_html
    - /bin/rm -rf $DEPLOYPATH/* $DEPLOYPATH/.* 2>/dev/null || true
    - /bin/cp -R pharmakon-app/frontend/out/* $DEPLOYPATH

